import { MigrationInterface, QueryRunner } from "typeorm";

export class FixNamingCases1775580704198 implements MigrationInterface {
    name = 'FixNamingCases1775580704198'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "FK_8efe7c679215735da4493f0bf80"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "FK_1799b360b8b068fa98feb7bef75"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "FK_11b2d89239496a9c9f4e374d795"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "FK_1a5f4f099a4ef32a948c977891f"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "FK_9da059c5e743d93d0a4c61aa830"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_d3c5f450939bf4fd56f844823cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbb463fe59980b5ea73f8e52b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05b49f1abfe4e65ef3f0fb698e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d95ea60a1c45f4f36981ac6d00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4798341f67bcbbea0b19716a3d"`);
        await queryRunner.query(`CREATE TABLE "app_user" ("appUserId" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "assignedById" uuid, "assignedToId" uuid, "appId" uuid, CONSTRAINT "PK_182fd00b9fb1dfbb1d888b36eac" PRIMARY KEY ("appUserId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_64f17db3ad78f5cd8c155a4fa7" ON "app_user" ("appId", "assignedToId") `);
        await queryRunner.query(`CREATE TABLE "app" ("appId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organizationId" uuid, "createdById" uuid, CONSTRAINT "PK_7ba9c9ca4cf02a4e3a8350e81fd" PRIMARY KEY ("appId"))`);
        await queryRunner.query(`CREATE TYPE "public"."membership_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TYPE "public"."membership_invitestatus_enum" AS ENUM('pending', 'accept', 'decline')`);
        await queryRunner.query(`CREATE TABLE "membership" ("membershipId" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying, "role" "public"."membership_role_enum" NOT NULL DEFAULT 'member', "inviteStatus" "public"."membership_invitestatus_enum" NOT NULL DEFAULT 'pending', "joinedDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedDate" TIMESTAMP NOT NULL DEFAULT now(), "invitedBy" character varying, "organizationId" uuid, "userId" uuid, CONSTRAINT "PK_fb7bd3f75d165f5f83de804c0d1" PRIMARY KEY ("membershipId"))`);
        await queryRunner.query(`CREATE TABLE "user_model" ("userId" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" text NOT NULL, "email" text NOT NULL, "passwordHash" character varying NOT NULL, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedDate" TIMESTAMP NOT NULL DEFAULT now(), "refreshToken" character varying, CONSTRAINT "UQ_864bd044bba869304084843358e" UNIQUE ("email"), CONSTRAINT "PK_4c45d8c361e22bb10f46be68f34" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "logLogTag" ("logId" uuid NOT NULL, "tagId" uuid NOT NULL, CONSTRAINT "PK_643b1ca8e9deef58ad1671efe06" PRIMARY KEY ("logId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_65b37db085f2081dc6a9e73909" ON "logLogTag" ("logId") `);
        await queryRunner.query(`CREATE INDEX "IDX_198465c35c71735635b9cd515e" ON "logLogTag" ("tagId") `);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "UQ_3c9751d2a6011ba13e27838105e"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "key_hash"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "key_prefix"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "last_used_at"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "subcomponent"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`DROP TABLE "log_log_tag"`)
        await queryRunner.query(`ALTER TABLE "log_tag" DROP CONSTRAINT "PK_3150d0b2a45872d8fade17760ef"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "tag_name"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "PK_350604cbdf991d5930d9e618fbd"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "sub_component_id"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "api_key_id"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "PK_472c1f99a32def1b0abb219cd67"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "organization_name"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "apiKeyId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "PK_bb44f960e117679a11f6b89bbcc" PRIMARY KEY ("apiKeyId")`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "keyHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "UQ_4aacb7c1641a74534c8a96c4dc9" UNIQUE ("keyHash")`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "keyPrefix" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "isActive" boolean`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "lastUsedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "expiresDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "apps" uuid`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "createdByAdminId" uuid`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "logTagId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD CONSTRAINT "PK_09c0dc8d131478ffe492d355d50" PRIMARY KEY ("logTagId")`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "tagName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "organizationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "log" ADD "logId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "PK_2a52ff321962f14587f210cd778" PRIMARY KEY ("logId")`);
        await queryRunner.query(`ALTER TABLE "log" ADD "logMessage" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "log" ADD "createdBy" uuid`);
        await queryRunner.query(`ALTER TABLE "log" ADD "appId" uuid`);
        await queryRunner.query(`ALTER TABLE "log" ADD "apiKeyId" integer`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "organizationId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "PK_7867970695572b3f6561516414d" PRIMARY KEY ("organizationId")`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "organizationName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "updatedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "createdById" uuid`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7fc0aea91cff3c22bc76684f76" ON "log_tag" ("organizationId", "tagName") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb5da66c79bb960c6aca75fe74" ON "log" ("appId", "createdDate") `);
        await queryRunner.query(`ALTER TABLE "app_user" ADD CONSTRAINT "FK_45a8318fff8e7b54ccfc09a9623" FOREIGN KEY ("assignedById") REFERENCES "user_model"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD CONSTRAINT "FK_ba6902c6e67561b5f15e737a946" FOREIGN KEY ("assignedToId") REFERENCES "user_model"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD CONSTRAINT "FK_ab2b6c1ca6939c84cedf0c83b8c" FOREIGN KEY ("appId") REFERENCES "app"("appId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "FK_e45915c9d4942bc6487f01c0dfe" FOREIGN KEY ("apps") REFERENCES "app"("appId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "FK_03cc85581f9e88eb22e115e6b6e" FOREIGN KEY ("createdByAdminId") REFERENCES "user_model"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "FK_a1f93025189ebe0b57c12de8496" FOREIGN KEY ("createdBy") REFERENCES "user_model"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "FK_7949b23ad7fa4169c56f7dc4f65" FOREIGN KEY ("appId") REFERENCES "app"("appId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "FK_e3c3fae9fff2bac91e83b791aec" FOREIGN KEY ("apiKeyId") REFERENCES "api_key"("apiKeyId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app" ADD CONSTRAINT "FK_7b9c9502e0197c9a959877f71d9" FOREIGN KEY ("organizationId") REFERENCES "organization"("organizationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app" ADD CONSTRAINT "FK_9b4630b0929fb82d39971970b17" FOREIGN KEY ("createdById") REFERENCES "user_model"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership" ADD CONSTRAINT "FK_4c62c8a7ba2337d6d6ffcd8eb6d" FOREIGN KEY ("organizationId") REFERENCES "organization"("organizationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership" ADD CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user_model"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_acdbd1e490930af04b4ff569ca9" FOREIGN KEY ("createdById") REFERENCES "user_model"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logLogTag" ADD CONSTRAINT "FK_65b37db085f2081dc6a9e739091" FOREIGN KEY ("logId") REFERENCES "log"("logId") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "logLogTag" ADD CONSTRAINT "FK_198465c35c71735635b9cd515e7" FOREIGN KEY ("tagId") REFERENCES "log_tag"("logTagId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "logLogTag" DROP CONSTRAINT "FK_198465c35c71735635b9cd515e7"`);
        await queryRunner.query(`ALTER TABLE "logLogTag" DROP CONSTRAINT "FK_65b37db085f2081dc6a9e739091"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_acdbd1e490930af04b4ff569ca9"`);
        await queryRunner.query(`ALTER TABLE "membership" DROP CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4"`);
        await queryRunner.query(`ALTER TABLE "membership" DROP CONSTRAINT "FK_4c62c8a7ba2337d6d6ffcd8eb6d"`);
        await queryRunner.query(`ALTER TABLE "app" DROP CONSTRAINT "FK_9b4630b0929fb82d39971970b17"`);
        await queryRunner.query(`ALTER TABLE "app" DROP CONSTRAINT "FK_7b9c9502e0197c9a959877f71d9"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "FK_e3c3fae9fff2bac91e83b791aec"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "FK_7949b23ad7fa4169c56f7dc4f65"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "FK_a1f93025189ebe0b57c12de8496"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "FK_03cc85581f9e88eb22e115e6b6e"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "FK_e45915c9d4942bc6487f01c0dfe"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP CONSTRAINT "FK_ab2b6c1ca6939c84cedf0c83b8c"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP CONSTRAINT "FK_ba6902c6e67561b5f15e737a946"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP CONSTRAINT "FK_45a8318fff8e7b54ccfc09a9623"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb5da66c79bb960c6aca75fe74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fc0aea91cff3c22bc76684f76"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "organizationName"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "PK_7867970695572b3f6561516414d"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "apiKeyId"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "appId"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "logMessage"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "PK_2a52ff321962f14587f210cd778"`);
        await queryRunner.query(`ALTER TABLE "log" DROP COLUMN "logId"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "organizationId"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "tagName"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP CONSTRAINT "PK_09c0dc8d131478ffe492d355d50"`);
        await queryRunner.query(`ALTER TABLE "log_tag" DROP COLUMN "logTagId"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "createdByAdminId"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "apps"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "updatedDate"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "expiresDate"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "lastUsedDate"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "keyPrefix"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "UQ_4aacb7c1641a74534c8a96c4dc9"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "keyHash"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "PK_bb44f960e117679a11f6b89bbcc"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP COLUMN "apiKeyId"`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "organization_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "log" ADD "api_key_id" integer`);
        await queryRunner.query(`ALTER TABLE "log" ADD "sub_component_id" integer`);
        await queryRunner.query(`ALTER TABLE "log" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "log" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "log" ADD "organization_id" integer`);
        await queryRunner.query(`ALTER TABLE "log" ADD "message" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "PK_350604cbdf991d5930d9e618fbd" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "organization_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "tag_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "log_tag" ADD CONSTRAINT "PK_3150d0b2a45872d8fade17760ef" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "subcomponent" integer`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "last_used_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "is_active" boolean`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "key_prefix" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "key_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "UQ_3c9751d2a6011ba13e27838105e" UNIQUE ("key_hash")`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_198465c35c71735635b9cd515e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65b37db085f2081dc6a9e73909"`);
        await queryRunner.query(`DROP TABLE "logLogTag"`);
        await queryRunner.query(`DROP TABLE "user_model"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`DROP TYPE "public"."membership_invitestatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."membership_role_enum"`);
        await queryRunner.query(`DROP TABLE "app"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64f17db3ad78f5cd8c155a4fa7"`);
        await queryRunner.query(`DROP TABLE "app_user"`);
        await queryRunner.query(`CREATE INDEX "IDX_4798341f67bcbbea0b19716a3d" ON "log" ("organization_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d95ea60a1c45f4f36981ac6d00" ON "log" ("created_at", "sub_component_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_05b49f1abfe4e65ef3f0fb698e" ON "log_tag" ("tag_name", "organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbb463fe59980b5ea73f8e52b0" ON "log_tag" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_d3c5f450939bf4fd56f844823cf" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "FK_9da059c5e743d93d0a4c61aa830" FOREIGN KEY ("api_key_id") REFERENCES "api_key"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "FK_1a5f4f099a4ef32a948c977891f" FOREIGN KEY ("sub_component_id") REFERENCES "sub_component"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "FK_11b2d89239496a9c9f4e374d795" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "FK_1799b360b8b068fa98feb7bef75" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "FK_8efe7c679215735da4493f0bf80" FOREIGN KEY ("subcomponent") REFERENCES "sub_component"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
